# Generated by Django 5.2.2 on 2025-06-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0002_alter_items_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='User_name',
            field=models.CharField(max_length=50),
        ),
    ]
